// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPJOQn4lqkNK77z5gQLmmrtTzP212br14',
    appId: '1:99421560629:web:3ae6075c55669b1cafb67c',
    messagingSenderId: '99421560629',
    projectId: 'ecomfull-89f42',
    authDomain: 'ecomfull-89f42.firebaseapp.com',
    storageBucket: 'ecomfull-89f42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ytsZPEx5kw3poLZuplJnpPX-1IJBqE4',
    appId: '1:99421560629:android:4e5d529ecaa9848fafb67c',
    messagingSenderId: '99421560629',
    projectId: 'ecomfull-89f42',
    storageBucket: 'ecomfull-89f42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHsCLi1bfzm5-mrjdzLLjd65hh6p278NA',
    appId: '1:99421560629:ios:ab7c92aaae623001afb67c',
    messagingSenderId: '99421560629',
    projectId: 'ecomfull-89f42',
    storageBucket: 'ecomfull-89f42.firebasestorage.app',
    iosClientId: '99421560629-4uceda9d3u11klem1q0nb8ngodrm3sco.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHsCLi1bfzm5-mrjdzLLjd65hh6p278NA',
    appId: '1:99421560629:ios:ab7c92aaae623001afb67c',
    messagingSenderId: '99421560629',
    projectId: 'ecomfull-89f42',
    storageBucket: 'ecomfull-89f42.firebasestorage.app',
    iosClientId: '99421560629-4uceda9d3u11klem1q0nb8ngodrm3sco.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuEcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPJOQn4lqkNK77z5gQLmmrtTzP212br14',
    appId: '1:99421560629:web:3afe2fa9792eb6e6afb67c',
    messagingSenderId: '99421560629',
    projectId: 'ecomfull-89f42',
    authDomain: 'ecomfull-89f42.firebaseapp.com',
    storageBucket: 'ecomfull-89f42.firebasestorage.app',
  );
}
